### ISSUE TITLE
Actor not updated when increasing the number of points in a Line using setPoints

### ISSUE THREAD

**Issue by RubendeBruin** [marcomusy/vtkplotter#31]
When an actor is made using Line(p0, p1) and later the number of vertices in increased using setPoints([p0,p1,p2]) then the polydata is updated but the additional line segment is not shown.

```
from vtkplotter import *

p0 = (0,0,0)
p1 = (1,1,1)
p2 = (-2,4,0)

L = Line(p0,p1, lw=4)    # <-- setup using two points
L.setPoints([p0,p1,p2])   # <-- increase to three points
print(L.getPoint(2))         # <-- the point is there

vp = Plotter(verbose=0)
vp += L

Lexpected = Line([p0,p1,p2]).c('black')
vp += Lexpected

vp.show()
```

I would expect the red line (initialized with two points, one added later) to overlap the black one (created from three points).

<img width="604" alt="temp" src="https://user-images.githubusercontent.com/34062862/59712272-300e8980-920d-11e9-82e8-c55e2e19a8ee.png">

**Comment by RubendeBruin** [comment]
The cause is that the Point data is updated but the line-data is not.
The following code would update the line-data as well:

```
# work-around
# (re-create the poly-line)

lines = L.poly.GetLines()
if lines:                                        # are we a lines-type actor
    n_points = L.NPoints()
    n_lines = lines.GetNumberOfCells()
    if n_lines != (n_points-1) :      # has the number of points changed?
        lines = vtk.vtkCellArray()    # Re-create the polyline.
        lines.InsertNextCell(n_points)
        for i in range(n_points):
              lines.InsertCellPoint(i)
        L.poly.SetLines(lines)
```

I could implement this in the SetPoints method and create a merge-request for this update, but wouldn't is have any side-effects?

**Comment by marcomusy** [comment]
Hi Ruben,
thanks for bringing up this issue, as you notice points are added but there is no way to know from inside setPoints() what is the cell connectivity for the point that is being added (either a line or some other polygon with other existing points)... so that would be a "side-effect": that would be only valid for lines.
Probably the easiest way is to recreate the longer line with `Line(points)`.
Another  possibility is to create a "line" made of N coincident points and then use `setPoints()` to modify it.

On the other hand this made me realize that a deletePoint() method might be useful.

Hope this helps.

**Comment by RubendeBruin** [comment]
Hi Marco, 

thanks for the support. 
The workaround works for me. And I do not see any robust modification either at this moment.

Should I close the issue or leave it open?
