### ISSUE TITLE
Visualize mesh segmentation

### ISSUE THREAD

**Issue by neoglez** [marcomusy/vtkplotter#54]
Hi Marco, i have been trying to visualize a mesh segmentation. That is: vertices with y-coordinate bellow y_n  get a color/class c_1, vertices with y-coordinate between y_n and y_m get a color c_2, and so forth but no success. The "bands" feature does not work because the intervals have the same length.
Is there a way to accomplish this?

**Comment by marcomusy** [comment]
You can use `cellColors()` this way:
```python
from vtkplotter import Sphere, settings
# settings.useDepthPeeling=True # not necessary if alpha=1

sv = Sphere().lw(0.1)

cols, alphas = [], []
for p in sv.cellCenters():
    if        p[2]>0.3:
        cols.append([1,0,0]) #rgb
    elif -0.2<p[2]<0.3:
        cols.append([0,1,0])
    else:
        cols.append([0,0,1])
    alphas.append(1)

sv.cellColors(cols, alpha=alphas, mode='colors')
sv.mapCellsToPoints() #optional
sv.show(axes=1, viewup='z')
```
![Screenshot from 2019-09-25 16-02-24](https://user-images.githubusercontent.com/32848391/65608179-19b35f00-dfae-11e9-95ce-a0b0720407c4.png)

**Comment by neoglez** [comment]
Thanks! You saved my day!
![segmented_mesh](https://user-images.githubusercontent.com/3646037/65611098-a2cc9500-dfb2-11e9-836c-782540740328.png)

**Comment by roaasoloh** [comment]
Hello @marcomusy 
Kindly how I may expand this code for more than three segments
I mean in my case, I'm extracting connected components of the mesh like this:
```
s = Sphere(res=12)
#some code for extracting connected components
getting this: [[0, 152, 162, 172, 182, 192, 202, 212, 222, 232, 2, 12, 22, 32, 42, 52, 62, 72, 82, 92, 102, 112, 122, 132, 142], 
[1, 41, 31, 21, 11, 241, 231, 221, 211, 201, 191, 181, 171, 161, 151, 141, 131, 121, 111, 101, 91, 81, 71, 61, 51], 
[3, 13, 23, 33, 43, 53, 63, 73, 83, 93, 103, 113, 123, 133, 143, 153, 163, 173, 183, 193, 203, 213, 223, 233, 234, 4, 14, 24, 34, 44, 54, 64, 74, 84, 94, 104, 114, 124, 134, 144, 154, 164, 174, 184, 194, 204, 214, 224, 225, 235, 5, 15, 25, 35, 45, 55, 65, 75, 85, 95, 105, 115, 125, 135, 145, 155, 165, 175, 185, 195, 205, 215, 216, 226, 236, 6, 16, 26, 36, 46, 56, 66, 76, 86, 96, 106, 116, 126, 136, 146, 156, 166, 176, 186, 196, 206, 207, 197, 187, 177, 167, 157, 147, 137, 127, 117, 107, 97, 87, 77, 67, 57, 47, 37, 27, 17, 7, 237, 227, 217, 218, 208, 198, 188, 178, 168, 158, 148, 138, 128, 118, 108, 98, 88, 78, 68, 58, 48, 38, 28, 18, 8, 238, 228, 229, 219, 209, 199, 189, 179, 169, 159, 149, 139, 129, 119, 109, 99, 89, 79, 69, 59, 49, 39, 29, 19, 9, 239, 240, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230]]
```
These are the indexes of points that belongs to a component

In this case it's three connected components, but what if it's more, as well how I define `sv.cellColors`?  Depending of what the constraints are set?

Thank you so much

**Comment by marcomusy** [comment]
sorry I don't understand your question!

**Comment by roaasoloh** [comment]
I'm trying to segment my mesh depending on the connected components I obtained,
each list above represent a region and I would like to color it unique color.

**Comment by marcomusy** [comment]
You can try with something like:
```python
import numpy as np
from vedo import *

settings.interpolateScalarsBeforeMapping = False # avoid full interpolation

s1 = Sphere(res=12).lw(1)

#some code for extracting connected components
groups = [[0, 152, 162, 172, 182, 192, 202, 212, 222, 232, 2, 12, 22, 32, 42, 52, 62, 72, 82, 92, 102, 112, 122, 132, 142],
[1, 41, 31, 21, 11, 241, 231, 221, 211, 201, 191, 181, 171, 161, 151, 141, 131, 121, 111, 101, 91, 81, 71, 61, 51],
[3, 13, 23, 33, 43, 53, 63, 73, 83, 93, 103, 113, 123, 133, 143, 153, 163, 173, 183, 193, 203, 213, 223, 233, 234, 4, 14, 24, 34, 44, 54, 64, 74, 84, 94, 104, 114, 124, 134, 144, 154, 164, 174, 184, 194, 204, 214, 224, 225, 235, 5, 15, 25, 35, 45, 55, 65, 75, 85, 95, 105, 115, 125, 135, 145, 155, 165, 175, 185, 195, 205, 215, 216, 226, 236, 6, 16, 26, 36, 46, 56, 66, 76, 86, 96, 106, 116, 126, 136, 146, 156, 166, 176, 186, 196, 206, 207, 197, 187, 177, 167, 157, 147, 137, 127, 117, 107, 97, 87, 77, 67, 57, 47, 37, 27, 17, 7, 237, 227, 217, 218, 208, 198, 188, 178, 168, 158, 148, 138, 128, 118, 108, 98, 88, 78, 68, 58, 48, 38, 28, 18, 8, 238, 228, 229, 219, 209, 199, 189, 179, 169, 159, 149, 139, 129, 119, 109, 99, 89, 79, 69, 59, 49, 39, 29, 19, 9, 239, 240, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230]]

pts =  s1.points()
pts0 = Points(pts[groups[0]], r=10, c='r')
pts1 = Points(pts[groups[1]], r=10, c='g')
pts2 = Points(pts[groups[2]], r=10, c='b')

ptdata = np.zeros_like(pts)
ptdata[groups[0]] = 0
ptdata[groups[1]] = 1
ptdata[groups[2]] = 2
s1.addPointArray(ptdata, "groupnumber")

# color mesh using vertex points
s1.cmap('jet_r', "groupnumber")

# map point data to cells (mesh faces) and color those
s2 = s1.clone() # make a copy
s2.mapPointsToCells().cmap('jet_r', on='cells')

show([(s1,pts0,pts1,pts2), s2], N=2, axes=1)
```
![Screenshot from 2021-05-21 11-13-47](https://user-images.githubusercontent.com/32848391/119113739-b2b9a800-ba25-11eb-951b-6221de8709a1.png)

**Comment by roaasoloh** [comment]
@marcomusy  I'm really appreciating your assitance, thank you so much,

One more idea if you please, what regarding more than 3 groups, in other word, ok. I'll be making a `for loop` dependable on `len(groups)` but my problem is how to assign different colors, how I shall assign these with different `c` : `pts0 = Points(pts[groups[0]], r=10, c='r')`
I was trying for the points(not regions, something like this:
```
  # keys = ['r','black','blue','white','green','purple']
    # pt = []
    # pts = []
    #
    # for i in component:
    #    print(i)
    #    for s, key in enumerate(keys):
    #        print(key)
    #        pt.append(Points(pts, c=key, r=7))
    # show(s, pt)
```
It's not giving correct results as well, :( 
but this assigns only for 5 colors, some one suggests to make `hexcolors` but also didn't worked, since I'm getting only the last color visualized, I'm not getting what I'm missing,
I don't want to depend on stick number, (5 here, or 3 in your example) instead I would like it to be dependable on the problem.
Much appreciated again.

**Comment by marcomusy** [comment]
this works for me:
```python
from vedo import *
import numpy as np

keys = ['r','black','blue','white','green','purple']
vpt = []
components= [0]

for i in components:
    for j, key in enumerate(keys):
        pts = np.random.rand(50, 3) + j
        vpt.append(Points(pts, c=key, r=7))

show(*vpt, "some other stuff", axes=1).close()
```
![Screenshot from 2021-05-24 15-48-43](https://user-images.githubusercontent.com/32848391/119357213-975dcf80-bca7-11eb-9f72-be436e3cce99.png)

**Comment by roaasoloh** [comment]
Sorry, I'm again re- asking after getting some trouble with this;
And again I'll try to clarify what I want,
I have a dynamic number of connected components, and I would like to color each region with different color, just like what this issue is opened for, but instead of only 3 colors, I might have more than 50 regions to color!
is it possible??
for example I have: 
```
14
[[0, 71, 70, 223, 184, 186, 236, 208, 193, 207, 194, 189, 190, 195, 206, 213, 209, 205, 215, 174, 339, 212, 197, 179, 177, 220, 286, 221, 204, 329, 258, 274, 255, 246, 268, 265, 334, 245, 267, 264, 271, 248, 256, 251, 244, 249, 275, 270, 58, 313, 314, 316, 164, 345, 319, 61, 259, 202, 253, 203, 328, 257, 247, 272, 266, 262, 335, 263, 336, 240, 241, 250, 276, 269, 59, 312, 315, 317, 163, 346, 320, 60, 260, 201, 254, 252, 243, 200, 311, 308, 318, 273, 309, 310, 199, 198, 239, 56, 116, 118, 119, 128, 122, 323, 347, 288, 113, 287, 325, 322, 121, 120, 324, 154, 114, 348, 289, 178, 180, 187, 196, 211, 210, 214, 171, 340, 238, 99, 337, 106, 293, 150, 52, 51, 321, 123, 117, 57, 242, 50, 151, 292, 109, 338, 98, 237, 43, 69, 291, 65, 75, 127, 342, 157, 112, 153, 155, 152, 294, 295, 296, 115, 156, 126, 341, 74, 66, 290, 68, 218, 172, 282, 107, 283, 108, 42, 344, 173, 40, 41, 67, 54, 146, 149, 148, 297, 145, 147, 162, 143, 161, 159, 124, 130, 100, 299, 298, 77, 300, 301, 62, 63, 168, 165, 226, 182, 216, 222, 181, 217, 224, 183, 185, 235, 188, 191, 192, 64, 53, 343, 176, 47, 111, 160, 110, 281, 46, 175, 219, 44, 45, 48, 73, 72, 125, 129, 103, 304, 305, 76, 303, 302, 285, 169, 170, 104, 78, 105, 279, 81, 82, 229, 85, 102, 280, 326, 133, 83, 80, 327, 131, 227, 228, 86, 132, 79, 231, 306, 135, 89, 332, 278, 232, 91, 92, 331, 90, 88, 137, 138, 94, 333, 277, 233, 307, 136, 93, 84, 230, 87, 134, 139, 140, 95, 330, 234, 96, 97, 167, 166, 284, 101, 225, 142, 144, 141, 158, 23, 25, 261, 26, 36, 35, 34, 24, 9, 49, 55, 16, 19, 29, 21, 8, 1, 2, 14, 11, 33, 4, 5, 7, 39, 32, 10, 37, 38], 
[3], 
[6], 
[12], 
[13],
 [15], 
[17], 
[18], 
[20],
 [22],
 [27], 
[28], 
[30], 
[31]]

```
I have here 14 regions, and as you notice, some vertices are single in the region!

I appreciate your assistance

**Comment by marcomusy** [comment]
> is it possible??

yes, obviously!
you can use a color map to transform a continuos scalar into a rgb color with
`rgb_col = colorMap(value, name=="jet", vmin=0, vmax=123)`

**Comment by roaasoloh** [comment]
I appreciate it if you may give me a sample example for my case?
Piece of code with the actuaL visualizations 

Much thankful

**Comment by roaasoloh** [comment]
> ```python
> show([(s1,pts0,pts1,pts2), s2], N=2, axes=1)
> ```

Please, for a mesh I tried, where I got also three connected components, I tried the quoted reply as it is, but the Visualization is not proper and same, it differs between the two, the attached shows what I mean,

 Also regarding the last reply from you, what should `value` means? since I tried it to be for components, it gives an error, tried it in a for loop for each of the connected component, it also didn't give any thing.

<img width="948" alt="Screen Shot 2021-06-16 at 1 26 22 PM" src="https://user-images.githubusercontent.com/29208631/122203753-07c2cf80-cea7-11eb-9a36-ce324ba1123d.png">

**Comment by marcomusy** [comment]
`value` is a real nr between vmin and vmax

sorry, i have no idea of what "connected components" is, your questions are not clear at all.

**Comment by roaasoloh** [comment]
Sorry,

I mean by connected components, the region(segment), that consists of single point or might be more, and I would like to visualize it.
Is there any reason why I’m getting different colormap, for the two meshes? I’m exactly applying your example for the three groups you mentioned earlier.

All what I asked more, if number of groups is dynamic, might be three one time, other time might be more(14, 20 … segments), I will need to assign different color for each group (segment) in order to visualize it, like the example you gave for the person mesh(instead of three colors (segments) it might be more)
