### ISSUE TITLE
"show" command modifies structures of underlying meshes

### ISSUE THREAD

**Issue by jacobdang** [marcomusy/vtkplotter#62]
When using the "show" command to display the polygon actor, I found that after using this command, the structure of the underlying polygon mesh is modified. That is, the number of vertices of the mesh is different after viewing the mesh.

Example: lungs_obj is an actor containing a mesh surface.  print(np.max(lungs_obj.getConnectivity())) # before using "show" command, it outputs "8707"
show(lungs_obj)
print(np.max(lungs_obj.getConnectivity())) # now it outputs "11902"

This should not happen, because that the "show" command is not supposed to modify its inputs. I am wondering how to avoid this phenomenon?

**Comment by marcomusy** [comment]
@jacobdang 
you are right in saying that the show() command should not modify what is shown... yet it's a bit tricky, because in order  to correctly manage the polygon smoothing vtk needs to compute normals and this causes that  some of the vertices are duplicated. Consider this example:
```python
from vtkplotter import *

#settings.computeNormals = True    # False by default

s = load(datadir+'mug.ply') # this mesh does not contain normals
t = s.clone()   # create a clone of the mesh to be shown, this will not be modified

print('before show', s.NPoints(), s.NCells()) # outputs "1725 3450"

show(s, verbose=0)

s.computeNormals()  # this causes the vertex duplication

print('after show ', s.NPoints(), s.NCells()) # now it outputs "2023 3450"

print('t NPoints', t.NPoints())
print('cleaned version of s', s.clean().NPoints())
```

### Possible solutions:
- create a clone of the mesh to be shown, this will not be modified.
- avoid creating normals for the mesh (if not needed).
