### ISSUE TITLE
GetNumberOfPoints Mismatch

### ISSUE THREAD

**Issue by unidesigner** [marcomusy/vtkplotter#9]
Hi, really great library! Many thanks for making this available.

One unexpected thing I ran into: I want to plot a colorcoded mesh (with values on the vertices, defined by colormaps). I computed the values for the vertices separately. I went through the mesh_coloring.py example. However, there seems to be a mismatch in the number of points returned by .N() with what is in the file, e.g. when I do vp.open("data/shuttle.obj") for instance, there are 660 points as output to .N(), whereas in the file, I see only 310 vertices. I run into this issue with some .STL files that I generated with the `meshio` library from NumPy.

Thanks for any pointers.

**Comment by marcomusy** [comment]
Hi!
thanks a lot for your interest.
Indeed when the `vtkPolyDataReader` object loads the mesh it duplicates vertices for some reason that is not very clear to me..
If you load the mesh with:
```python
shu = vp.load('data/shuttle.obj').clean()
print(shu.N()) # 310 points
```
instead of `vp.load('data/shuttle.obj')`, then coincident points are merged..
`clean()` just wraps https://vtk.org/doc/nightly/html/classvtkCleanPolyData.html

**Comment by unidesigner** [comment]
This solves the issue, many thanks! Perhaps the .clean() call should be default for polydata load's as it is quite unexpected and not sure why more point are generated.

**Comment by marcomusy** [comment]
It was actually the default in previous versions, but for large meshes loading was slower and I had a couple of other issues so I removed it..
